### ISSUE TITLE
Remove OCDS specific things from here

### ISSUE THREAD

**Issue by rhiaro** [OpenDataServices/lib-cove#43]
OCDS-specific code (eg. things referencing ocid, or records/releases) should be moved to lib-cove-ocds at some point.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor OCDS-specific code into a new application](https://trello.com/c/6SyOfmT6/49-refactor-ocds-specific-code-into-a-new-application)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor OCDS-specific code into a new application](https://trello.com/c/AZzrHNSN/66-refactor-ocds-specific-code-into-a-new-application)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove all OCDS-specific CoVE code from shared CoVE libs](https://trello.com/c/YFV9kqwY/67-remove-all-ocds-specific-cove-code-from-shared-cove-libs)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document the areas of code that remain to be removed from shared CoVE repos](https://trello.com/c/cXZmjMT3/72-document-the-areas-of-code-that-remain-to-be-removed-from-shared-cove-repos)

**Comment by Bjwebb** [comment]
Done in https://github.com/OpenDataServices/lib-cove/pull/55
