### ISSUE TITLE
Lock verson of Black in this repo (see Travis file)?

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/lib-cove#58]
We do in other places, and it avoids things like #57

**Comment by jpmckinney** [comment]
Closed by https://github.com/OpenDataServices/lib-cove/commit/93157920e67d14ca80502a7ca73901bfaf0f5fd3

**Comment by jpmckinney** [comment]
@Bjwebb You can close this issue to declutter issue tracker.
