### ISSUE TITLE
Don't use os.rename - it does not work across file systems

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/lib-cove#84]
We have seen an error on a dev machine - "Invalid cross-device link" - caused by os.rename in get_orgids_prefixes func(). 

https://github.com/OpenDataServices/lib-cove/blob/main/libcove/lib/common.py#L1344

This error seems to be coming up because on this dev machine a VM with  a shared drive for the code was being used, so that /tmp and and the virtualenv directory where on different drives - and sometimes rename will fail in this case.

https://docs.python.org/3/library/os.html#os.rename

>  The operation may fail on some Unix flavors if src and dst are on different filesystems.

In theory, this could happen on live servers too.

**Comment by jpmckinney** [comment]
Can now be closed (#115 was merged via #122 so it didn’t autoclose)

**Comment by jpmckinney** [comment]
@duncandewhurst can close.
